# fly.toml app configuration file generated for one-hard-thing on 2025-09-23T11:10:11-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'one-hard-thing'
primary_region = 'dfw'

[build]

[env]
  PORT = "8000"  # uvicorn already binds to 8000; Fly sets $PORT anyway

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    type = "http"
    method = "get"
    path = "/health"
    interval = "10s"
    timeout = "2s"
    grace_period = "10s"
